### ISSUE TITLE
10995a9ca4ec300caf3c2954b083cc919e4d2490

### ISSUE THREAD

**Issue by jiminjung2334** [ksj64381/testing-repo#2]
10995a9ca4ec300caf3c2954b083cc919e4d2490 <- 커밋 id입니다.

본인 학과에 대한 정보가 필요하다고 생각되어 
202100796 김승진 -> 202100796 김승진 컴퓨터공학과로 커밋하였습니다
참고해주세요!

**Comment by ksj64381** [comment]
e91dc046ceaf60f679c0aed127fb3234465caaa2
고쳐드렸습니다~
